In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

In [2]:
engine = create_engine("mysql+pymysql://root:jgd1305@localhost/class_db")

In [3]:
engine.connect()

In [4]:
df = pd.read_excel('E:\SQL\child_test_score.xlsx')
df2 = pd.read_excel('E:\SQL\location_master.xlsx')
df3 = pd.read_csv('E:\SQL\child_register.csv')

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:3: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:3: SyntaxWarning: invalid escape sequence '\S'
C:\Users\window 10\AppData\Local\Temp\ipykernel_16460\2836238221.py:1: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_excel('E:\SQL\child_test_score.xlsx')
C:\Users\window 10\AppData\Local\Temp\ipykernel_16460\2836238221.py:2: SyntaxWarning: invalid escape sequence '\S'
  df2 = pd.read_excel('E:\SQL\location_master.xlsx')
C:\Users\window 10\AppData\Local\Temp\ipykernel_16460\2836238221.py:3: SyntaxWarning: invalid escape sequence '\S'
  df3 = pd.read_csv('E:\SQL\child_register.csv')

Replication - Staging

In [5]:
df.to_sql("staging1", engine, if_exists="replace", index=False)
df2.to_sql("staging2", engine, if_exists="replace", index=False)
df3.to_sql("staging3", engine, if_exists="replace", index=False)

5000

Check Null Values  for select statements we can use python read sql query byt for create statements we need to call engine CREATE TABLE is a DDL statement
It needs commit
engine.begin() auto-commits safely

working on two columns age and dob as both are related

In [6]:
df_data = pd.read_sql_query("SELECT dob FROM staging3 LIMIT 5;", engine)
print(df_data)

          dob
0  2011-02-14
1  2010-01-01
2        None
3  2010-01-16
4  2012-02-02

from excel sheet we analyze that age is 0 only when dob is given ( extract age from dob)

In [7]:
df_preview = pd.read_sql_query("""
SELECT registration_no, age, dob
FROM staging3
WHERE age = 0 AND dob IS NOT NULL
LIMIT 10
""", engine)

print(df_preview)

                                  registration_no  age         dob
0  000QzCDgxPdpi8uodbHU7ouJeIzbSt2020120314432652    0  2011-02-14
1  01DhWt0ibpEZqWaGj5dSSms05JRpSP2020121211300220    0  2010-01-01
2  021tNKbCnNvDxNpLJvZJtH7eF7HudF2020102020491494    0  2010-01-16
3  02NDpyY1JcazqWp0hJsok6FEdRy6sa2020113012213018    0  2012-02-02
4  02gCp8o6BKDnnNTJndWtyZSulj687v2020120714015235    0  2009-06-06
5  03tFgnBI9Vlv6uYbAb44NylvNyruGs2020120315151546    0  2013-12-10
6  06iBIlXQ3S7YL0EXcX4WxVL2rRtMY32020111813062923    0  2010-01-01
7  08vxysh3RVeB18rnnxYS9pJmiZONEa2020120820101965    0  2013-01-01
8  0AETmmxLnDnjYHgxsJ763TNmo3UCyT2020113015300338    0  2010-01-01
9  0DHQEUOvpmATztCjS3ZOIo6U1v29BR2020102713261972    0  2010-06-06

setting age from year and currentdate where age is zero and dob is not null

In [8]:
# Execute UPDATE query
with engine.begin() as conn:
    conn.execute(text("""
        UPDATE staging3
        SET age = TIMESTAMPDIFF(YEAR, dob, CURDATE())
        WHERE age = 0 AND dob IS NOT NULL
    """))

print("Age updated successfully!")

Age updated successfully!

after setting age

In [9]:
df_after = pd.read_sql_query("""
SELECT registration_no, age, dob
FROM staging3
WHERE dob IS NOT NULL
LIMIT 10
""", engine)

print(df_after)

                                  registration_no  age         dob
0  000QzCDgxPdpi8uodbHU7ouJeIzbSt2020120314432652   15  2011-02-14
1  01DhWt0ibpEZqWaGj5dSSms05JRpSP2020121211300220   16  2010-01-01
2  021tNKbCnNvDxNpLJvZJtH7eF7HudF2020102020491494   16  2010-01-16
3  02NDpyY1JcazqWp0hJsok6FEdRy6sa2020113012213018   14  2012-02-02
4  02gCp8o6BKDnnNTJndWtyZSulj687v2020120714015235   16  2009-06-06
5  03tFgnBI9Vlv6uYbAb44NylvNyruGs2020120315151546   12  2013-12-10
6  06iBIlXQ3S7YL0EXcX4WxVL2rRtMY32020111813062923   16  2010-01-01
7  08vxysh3RVeB18rnnxYS9pJmiZONEa2020120820101965   13  2013-01-01
8  0AETmmxLnDnjYHgxsJ763TNmo3UCyT2020113015300338   16  2010-01-01
9  0DHQEUOvpmATztCjS3ZOIo6U1v29BR2020102713261972   15  2010-06-06

In [10]:
df_set = pd.read_sql_query("SELECT * FROM staging3", engine)
df_set.head()

,registration_no,name,gender,age,dob,village_code
0,000QzCDgxPdpi8uodbHU7ouJeIzbSt2020120314432652,moti,M,15,2011-02-14,0F8B8EA90ED9465889E625B93
1,01DhWt0ibpEZqWaGj5dSSms05JRpSP2020121211300220,Laxmi,F,16,2010-01-01,101801A9CC18489D856CFEA8F
2,01waDXsScvbXroEGDCSJ6ZnrBh0JOe2020120912585126,Jigar,M,3,None,12C65E78B3214F40BC6990E81
3,021tNKbCnNvDxNpLJvZJtH7eF7HudF2020102020491494,Niti ka,F,16,2010-01-16,114D7E49FDAE4B4880EE8DFCA
4,02NDpyY1JcazqWp0hJsok6FEdRy6sa2020113012213018,Ankit,M,14,2012-02-02,0B6572DFB0D243F5841C5D954

let's now check dublicates

In [11]:
df = pd.read_sql_query("""
SELECT registration_no, COUNT(*) AS count
FROM staging3
GROUP BY registration_no
HAVING COUNT(*) > 1
""", engine)

print(df)

Empty DataFrame
Columns: [registration_no, count]
Index: []

In [ ]:
with engine.begin() as conn:
    conn.execute(text("""
        UPDATE staging3
        SET estimated_birth_year = YEAR(CURDATE()) - age
        WHERE 
        age IS NOT NULL
    """))

In [14]:
df = pd.read_sql_query("""select * from staging3""", engine)
print(df)

                                     registration_no     name gender  age  \
0     000QzCDgxPdpi8uodbHU7ouJeIzbSt2020120314432652     moti      M   15
1     01DhWt0ibpEZqWaGj5dSSms05JRpSP2020121211300220    Laxmi      F   16
2     01waDXsScvbXroEGDCSJ6ZnrBh0JOe2020120912585126   Jigar       M    3
3     021tNKbCnNvDxNpLJvZJtH7eF7HudF2020102020491494  Niti ka      F   16
4     02NDpyY1JcazqWp0hJsok6FEdRy6sa2020113012213018   Ankit       M   14
...                                              ...      ...    ...  ...
4995  YhFSIwdWm0whVNyNh2mnUBGZ0aBL3A2020112420195207    Savan      M    8
4996  YhIgxnpRlpPI8tS0gMfLezDuIcjraX2020112321125477   kartik      M   10
4997  YhqIh2jgn75hvdVnm2fr8ylpjo2nIN2020113013142750    Akish      M   16
4998  YioPPjquhFahdC9wdTogEv2GlVbyKb2020120115131066    madhu      F    8
4999  YjQHRi2FdkxAeotCJb3wXKrRRaQKfM2020121115494251   govied      M    8

             dob               village_code
0     2011-02-14  0F8B8EA90ED9465889E625B93
1     2010-01-01  101801A9CC18489D856CFEA8F
2           None  12C65E78B3214F40BC6990E81
3     2010-01-16  114D7E49FDAE4B4880EE8DFCA
4     2012-02-02  0B6572DFB0D243F5841C5D954
...          ...                        ...
4995        None  12544221CECF4D43990753043
4996        None  082DE0A566344A51B8EA3CBB9
4997  2009-10-05  0A2FE6B40BC04D7EA0AE67921
4998        None  07CCC9D60F1849C2863153510
4999        None  0E9345B978034C2D8077E76E9

[5000 rows x 6 columns]

In [16]:
df = pd.read_sql_query(""" select * from staging1""", engine)
print(df)

                                     registration_no  hindi  english  math  \
0     Sh0vVvpM3r54xnhMts1IFpflJRdVwN2020112809375056     11        9    11
1     BPPjBnW3jHeFFOxaJThKTTzEgVTioh2020113010265466      4        0     3
2     WB8oDoSEnkD5P19dNzfxFfdgLiqfmR2020111815555617     11       11     9
3     JvlEqG7ceLjUiykY9UqXzYUq9VV6uz2020113013274872      9        4     5
4     QRjpJCrSrrem1UJnC19mzqTaz827i32020120414021403      5        3     6
...                                              ...    ...      ...   ...
3931  L2HuKb8szXb8XFX5EeApkfEbY6xYFj2020120712174967     11       11     9
3932  5tFCFQL1V9lCyzjWsBoSHx22o0h0CM2020120712212307     11       11    10
3933  6ID6zBEtGhGgcMa7txC3ojNpuF2URj2020120712032355      8       10    10
3934  GiBlZbD8zyAjEQzMBRAF9YIBYh6kg32020120712153501     11       11    11
3935  Dxvim0K7BxkPRvG0wwpzb7VOR5gaRG2020120712045946     11       11    10

      science
0           5
1           0
2           6
3           1
4           5
...       ...
3931       11
3932       11
3933       11
3934       11
3935       10

[3936 rows x 5 columns]

Checking duplicates in this child_test_score file

In [ ]:
location = pd.read_sql_query("""
select * from staging2""", engine)
print(location)

     district         block                  village  \
0    BANSWARA   GANGADTALAI               GAMANAMALA
1        DHAR          DAHI                  THANDLA
2      JHABUA    PETLAWAD 1                    UNNAI
3    BANSWARA  SAJJANGARH 1               JOGRI MATA
4      JHABUA       THANDLA               BHAIROGARH
..        ...           ...                      ...
195   KHANDWA     BADWAHA 2                    AARSI
196      DHAR     NALCHHA-1              NAZIKBARODA
197   UDAIPUR       GIRWA 1                   GOVALA
198  JHALAWAR         DAG 2                SALARIYA3
199   UDAIPUR         MAVLI  NP_FATEH_SAN WARD NO. 4

                  village_code
0    0010B1383BF6432DB28085159
1    0013273B4D374E8E8B7BFF58B
2    00172BC3B0D541CEA09386834
3    0029D2E7D95349F8B0AF52E18
4    002A2533D59F49F0B29B4B590
..                         ...
195  07D2E25A9B5D48FFB9FE4BA89
196  07D3D71C4BDC48398AD9FF746
197  07E582D13C074DD0B392FD973
198  0810DF29EBE5462E942469FC4
199  0811B6F027EA41AB8899617F7

[200 rows x 4 columns]

Q1 Which is the largest block based on number of villages within? How many villages are there in the block? the blockis in which district?
ans: MALVI with 9 villages and dsitrict UDAIPUR

In [17]:
nblock = pd.read_sql_query("""
SELECT district, block, Count(village) as numvill
from staging2
group by  district , block
ORDER BY numvill DESC
limit 1 """, engine)
print(nblock)

  district  block  numvill
0  UDAIPUR  MAVLI        9

Q2 Which district has highest no. of girls registered for the test ? How many are registered un the dsitrict?
ans: BANSWARA  has highest registred girls equal to 265

In [18]:
pd.read_sql_query("""
SELECT lm.district, cr.gender ,
COUNT(cr.registration_no) AS girl_count
from staging2 lm 
JOIN staging3 cr
ON lm.village_code = cr.village_code 
WHERE cr.gender = 'F'
Group by lm.district
ORDER by girl_count DESC
LIMIT 1 """ , engine)

   district gender  girl_count
0  BANSWARA      F         265

 Q3 Write a query to display the registartion_no , name and gender of children who have not  apperaed for the test . Arrange tyhe rows in asending aplhabatical order of name.

In [19]:
pd.read_sql_query("""
SELECT cr.registration_no , cr.name , cr.gender
FROM staging3 cr
LEFT JOIN staging1 cs
ON cr.registration_no = cs.registration_no
WHERE cs.registration_no is null
ORDER BY cr.name ASC
""", engine)

                                     registration_no             name gender
0     JemQIBS17SxT2n0kYlvObtfWzqSG1o2020102620354767           Saloni      F
1     IekPdnjmaRkWlQ2RspbkxmBa3122gl2020112820353658    Rupa prjapati      F
2     52NSKwK7TrowQl4jaAQuGnouNqMWli2020112820012795   Soniya agariya      F
3     CQRYCWZPDKI56wvKbpdeReVJMV0yg82020102814311210           aachal      F
4     YA6aSpPiDdykfHdqdpt8StnhEhQJp62020101911141365           aaguri      F
...                                              ...              ...    ...
1161  OQUU428gpB0BZYvetanGTkInTmqXxk2020112418512269      Vivek Gamad      M
1162  LmmwwaNFz30Zl3iZEqzwYzapvktofp2020102414320479          Yashoda      F
1163  3d81h8YORXIDZ6gFl191JGuYnQMnOU2020111713192376           yasmin      F
1164  5bnT5DkrIG9ilBztans7XuUYosLM5N2020120213321520           yavraj      M
1165  5AAtBzfvSUJlgxd4Bzk4EZGz3C7V1h2020101610125721     YUVRAJ SINGH      M

[1166 rows x 3 columns]

Q4 Red, Amber, Green , gradees are given based onthe following rules:
if the total rest score in all 4 subjects is <20 then red >=20 and < 30 then Amber >=30 the green 
Write a query to grades of the students , such that each row contains the district , block cillage , village_code. student_anme , gender, age , grade in desc prder of total score

In [ ]:
pd.read_sql_query(""" 
    WITH CTE1 AS (
     SELECT registration_no,
     (hindi + science + english + math) AS total_score,
      CASE
        WHEN (hindi + science + english + math) < 20 THEN 'Red'
        WHEN (hindi + science + english + math) >= 20 
         AND (hindi + science + english + math) < 30 THEN 'Amber'
        ELSE 'Green'
        END AS grade
     FROM staging1
    )

    SELECT cr.name,cr.gender, cr.age, lm.district, lm.block, lm.village, lm.village_code, CTE1.grade, CTE1.total_score
    FROM staging2 lm
    join staging3 cr
    on lm.village_code= cr.village_code
    join CTE1 
     ON cr.registration_no = CTE1.registration_no
    ORDER BY CTE1.total_score DESC
    """, engine)

,name,gender,age,district,block,village,village_code,grade,total_score
0,Prakash,M,18,KHALWA,KHALWA,KOTWARIA FV,02C9BEADA438439E889756FA0,Green,41
1,badal,M,12,SALUMBER,RISHABHDEV,KALAVATPALA,00E1654BC73247E6AB2776BA9,Green,41
2,suman,F,12,SALUMBER,RISHABHDEV,KALAVATPALA,00E1654BC73247E6AB2776BA9,Green,41
3,Monika Goswami,F,11,UDAIPUR,MAVLI,NANDOLI KHURD,0704C55FCB164D66A7341D576,Green,41
4,Tanisha Lohar,F,13,UDAIPUR,MAVLI,NANDOLI KHURD,0704C55FCB164D66A7341D576,Green,41
...,...,...,...,...,...,...,...,...,...
1571,ankit,M,10,BANSWARA,BANSWARA 2,SAMAPADA,0114095C99504A8C8F14D2AA3,Red,4
1572,reetesh,M,9,BANSWARA,BANSWARA 2,SAMAPADA,0114095C99504A8C8F14D2AA3,Red,3
1573,kalpesh,M,5,UDAIPUR,KOTRA 3,UPLI SUBRI,014E6AB55458467E9952EE1EE,Red,3
1574,pooja,F,6,KHANDWA,BADWAHA 2,AMBA,03CACA46B862451C8FC18FF98,Red,3
1575,Shivani,F,6,KHANDWA,BADWAHA 2,AMBA,03CACA46B862451C8FC18FF98,Red,3

Q5  Write A query to find the top ranking student in each age based on Total score obtained in all subjects. If there is more than 1 student with higest score , then select 1 student in reverse alphabetical order

In [ ]:
pd.read_sql_query("""
WITH score_cte AS (

SELECT
cr.registration_no,cr.name,cr.age,
(cs.hindi + cs.science + cs.english + cs.math) AS total_score,

ROW_NUMBER() OVER(
PARTITION BY cr.age
ORDER BY 
(cs.hindi + cs.science + cs.english + cs.math) DESC,
cr.name DESC
) AS rank_no

FROM staging1 cs JOIN staging3 cr
ON cs.registration_no = cr.registration_no
)

SELECT
name,age,total_score
FROM score_cte
WHERE rank_no = 1
ORDER BY age;

""", engine)

                    name  age  total_score
0         delip  banjara    3           32
1                 Reshma    4           35
2                  chotu    5           30
3                 Yogesh    6           39
4                Shivani    7           41
5            SUMAN RAGER    8           41
6            MAYA RAGER     9           41
7                 vinod    10           41
8                vikram    11           41
9        laduram laduram   12           43
10          Tulsi gameti   13           44
11          Sapna gameti   14           42
12  SEEMA KUMARI BAIRWA    15           41
13   VIMLA KUMARI BHEEL    16           41
14                Mangal   17           41
15              virendra   18           41
16                 Rohit   19           41
17                Aakash   20           41

Q6 Write a query to display the list of all villages where 10 or more girls have appeared inthe test in descending order of numer of girls.

In [36]:
pd.read_sql_query(""" 
select lm.village, 
count(cr.gender) as count
from staging2 lm 
join staging3 cr
on 
lm.village_code = cr.village_code
join staging1 cs
on
cr.registration_no = cs.registration_no 
where gender = 'F' and cr.registration_no is not null
group by lm.village 
having count(cr.gender) >=10
order by count desc
 """, engine )

        village  count
0      BHATEWAR     13
1        GADOLI     12
2  BANKA KHUNTA     11
3    BHAIROGARH     11
4          AMJA     11
5     ANANDPURI     11
6       THANDLA     10
7        SADEDA     10

 Q7. Do you see any anomaly/irregularity in the age field of the child_register? Can you suggest a way to resolve this?
ans:
yes age is given in dataset is 3 , which is an outlier, using standard deviation and taking mean or IQR method we can resolve this. Age can be derived from dob and as analyzed where age= 0 dob is given from there we can derive age values.(done in above shells)

TASK 2 DASHBOARD